services:
  # Project
  plasticine-monitor:
    container_name: plasticine-monitor
    build:
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    networks:
      - mongo
    depends_on:
      - mongo

  # MongoDB
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: plasticine-monitor
    volumes:
      - mongo:/data/db:rw

networks:
  mongo:

volumes:
  mongo:
